version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - cd frontend && npm install --legacy-peer-deps
      - cd backend && npm install --legacy-peer-deps
      - echo "📦 installing Front-end Back-end packages..."
      - echo "✅ Packages Front-end Back-end installed successfully."
  build:
    commands:
      - cd frontend && npm run build --force
      - echo "⚙️ Testing..."
      - echo "✅ Tests passed successfully."
      - echo "🚧 Starting Front-end compiling packages..."
      - echo "✅ Build Front-end passed successfully."
artifacts:
  files:
    - frontend/build/*/ # Артефакты фронтенда
    - backend/server.js    # Файл сервера из бэкенда
